version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: nestjs_postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: aaaa
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nestnet

volumes:
  postgres_data:

networks:
  nestnet:
    driver: bridge
